import Footer from "@/components/footer";
import Header from "@/components/header";
import Podpora from "@/components/podpora";
import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header />

        {children}
        {/* <Podpora /> */}
        <Footer />
      </body>
    </html>
  );
}
