export const newsData = [
  //   {
  //     title: "Pitchfork Kickstarter Taxidermy",
  //     subtite: "vylet",
  //     datum: "11.11.2024",
  //     text: "Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.",
  //     img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399715/svoucestou.info/433280086_957915323004435_780922250576987527_n.webp",
  //     url: "/news",
  //   },https://res.cloudinary.com/dam7wdzvx/image/upload/v1746256962/svoucestou.info/news/mozaika1.webp
  {
    title: "Přístřešek pro pec na chleba",
    subtite: "stavba",
    datum: "15.května 2025",
    text: "Začínáme stavět přístřešek pro naši pec na chleba, která bude následovat! Zatím jen pár trámků, ale už teď se těšíme, až tu zavoní první bochník. Pomalu a poctivě budujeme místo, kde se bude dobře péct i potkávat.",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1747321896/svoucestou.info/news/155.webp",
    url: "/news",
  },
  {
    title: "Včelky se rozhodly vyrojit!",
    subtite: "včely",
    datum: "2.května 2025",
    text: "Dnes bylo u nás pěkně rušno – včelky se rozhodly vyrojit! Naštěstí všechno dobře dopadlo a roj jsme bezpečně usadili zpátky do úlu. Teď už zase pilně pracují tam, kde mají. Díky, přírodo, za tohle krásné divadlo!",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1747321896/svoucestou.info/news/025.webp",
    url: "/news",
  },

  {
    title:
      "Návštěva botanické zahrady: mikroskopování, masožravky a nový kamarád...",
    subtite: "exkurze",
    datum: "březen 2025",
    text: "Vyrazili jsme do botanické zahrady, kde děti měly možnost nahlédnout do fascinujícího světa rostlin. Užily si mikroskopování, objevovaly skryté detaily přírody a v pavilonu Fata Morgana se zúčastnily poutavé přednášky o masožravých rostlinách. A to nejlepší? Neodjely jsme s prázdnou – přivezly jsme si nového třídního mazlíčka, strašilku Karla!",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1742374758/svoucestou.info/news/1.webp",
    url: "/news",
  },
  {
    title: "Návštěva u adolescentů v Mozaice (Mnichovice)",
    subtite: "exkurze",
    datum: "20.11.2024",
    text: "Navštívili jsem kamarády v Mozaice (Mnichovice), aby jsme zjitili jak se jim daří a načerpali inspiraci do dalších školních projektů. Dětem se otevřely oči, když viděly, co vše je možné a ihned začaly plánovat. Nám dospělým návštěva pomohla se ujistit, že jdeme správnou cestou a velmi jsem si užili společný čas v jiném prostředí.",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1746256962/svoucestou.info/news/mozaika1.webp",
    url: "/news",
  },
  {
    title: "Objevujeme krásy okolní přírody!",
    subtite: "turistika",
    datum: "listopad 2024 - únor 2025",
    text: "Naše děti se pravidelně vydávají na turistické výpravy za poznáním a dobrodružstvím. Při svých cestách objevují nejen malebné lesní stezky a tajuplné jeskyně, ale i zapomenuté mlýny a mokřady. Pozorují koně a ovce na pastvinách, divoká zvířata v jejich přirozeném prostředí a dokonce i exotické druhy ptactva. Každý výlet je novým objevem a příležitostí k učení skrze vlastní zkušenost.",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1742374758/svoucestou.info/news/3.webp",
    url: "/news",
  },
  {
    title: "Navštívili nás budoucí učitelé",
    subtite: "návštěva",
    datum: "červen 2024",
    text: "Naši školu oslovila brněnská spolecnost Lipka s prosbou, zda by mohli učitelé z klasických škol přijet na exkurzi k nám. Zkušený páťák je provedl školou, představil jim vybrané učební pomůcky a ukázal venkovní prostory, které využíváme pro školní projekty starších žáků.",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399713/svoucestou.info/448996529_1032759518853348_1351890881870249553_n.webp",
    url: "/news",
  },
  {
    title: "Školní zahrada a pěstování zeleniny",
    subtite: "zemědělství",
    datum: "jaro 2024",
    text: "S našimi staršími školáky jsme společnou prací vytvořili záhonky pro zeleninu. Děti se učí praxí a zároveň si užívají čas venku. Už se těšíme na první sklizeň.",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399721/svoucestou.info/465124396_1139228408206458_6170646010298287825_n.webp",
    url: "/news",
  },
  {
    title: "Školní včely",
    subtite: "včely",
    datum: "jaro 2024",
    text: "Starší školáci se rozhodli pořídit včely a vše potřebné pro jejich chov s pomocí našeho zkušeného Martina. Společně vybrali místo, připravili úly a potřebné vybavení. Martin je postupně učí, jak se o včely starat, kontrolovat jejich zdraví a na jaře bude snad první med.",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399708/svoucestou.info/438785437_984960693633231_8534910202200475632_n.webp",
    url: "/news",
  },
];
