export const tymData = [
  {
    titulPred: "Bc. ",
    titulZa: ", DiS.",
    name: "Běla Šestáková",
    title: "zakladatelka, průvodkyně pro školku i školu",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399635/svoucestou.info/pruvodci/B.webp",
    klass: "",
    facebook: "https://www.facebook.com/montessori.guru",
    instagram: "https://www.instagram.com/svoucestou/",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "https://montessori.guru/",
  },
  {
    titulPred: "Mgr. ",
    name: "Kateřina Paseková",
    title: "průvodkyně ve škole",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399634/svoucestou.info/pruvodci/K.webp",
    klass: "",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    name: "Růžena Šindelářová",
    title: "průvodkyně ve školce",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1734088562/svoucestou.info/pruvodci/ru2.webp",
    // img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399634/svoucestou.info/pruvodci/M.webp",
    klass: "",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    name: "Steve",
    title: "lektor anglického jazyka (rodilý mluvčí) a chovatel psů",
    claim: "moje motto",
    img: "/person.png",
    // img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399634/svoucestou.info/pruvodci/M.webp",
    klass: "",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    titulPred: "Ing. ",
    titulZa: ", DiS.",
    name: "Michaela Vávrová",
    title: "pohybové aktivity a turistika",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1734088562/svoucestou.info/pruvodci/misa2.webp",
    // img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399634/svoucestou.info/pruvodci/M.webp",
    klass: "",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    name: "Nikola Smejkalová",
    title: "velmi laskavě zaskakující průvodkyně ve školce",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1734088562/svoucestou.info/pruvodci/niko2.webp",
    klass: "",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    name: "Tomáš Nebeský",
    title: "pohybové aktivity a turistika",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1737387022/svoucestou.info/pruvodci/tomas.webp",
    klass: "",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    // cross: "nyní v zahraničí",
    name: "Martin Yo",
    title: "pohybové aktivity a hry",
    claim: "moje motto",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399634/svoucestou.info/pruvodci/M.webp",
    // img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399634/svoucestou.info/pruvodci/M.webp",
    // klass: "opacity-40",
    facebook: "",
    instagram: "",
    linkedin: "",
    web: "",
    web2: "",
    eshop: "",
  },
  {
    name: "Zbyněk Svoboda",
    title: "IT, zahrada, hry",
    claim: "nic není nemožné, toyota",
    img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1685532355/zbyneksvoboda/me_smhw9x.webp",
    // img: "https://res.cloudinary.com/dam7wdzvx/image/upload/v1732399635/svoucestou.info/pruvodci/Z.webp",
    klassImg: "object-top",
    klass: "",
    facebook: "https://www.facebook.com/profile.php?id=100093105173892",
    instagram: "https://www.instagram.com/zbyndasvoboda/",
    linkedin: "https://www.linkedin.com/in/zbyneksvoboda/",
    web: "https://www.zbyneksvoboda.cz/",
    web2: "",
    eshop: "",
  },
];
